=== Ruhithpasha/College_web_dev/punith/student.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="student">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string" />
                <xs:element name="studentInfo"  maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="studentName" type="xs:string" />
                            <xs:element name="studentId" type="xs:string" />
                            <xs:element name="studentAge" type="xs:integer" />
                            <xs:element name="studentGender" type="xs:string" />
                            <xs:element name="course" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="studentsubjects">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="firstsubject" type="xs:string" />
                            <xs:element name="secondsubject" type="xs:string" />
                            <xs:element name="thirdsubject" type="xs:string" />
                            <xs:element name="fourthsubject" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="activities">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="curicularactivities" type="xs:string" />
                            <xs:element name="sportsactivities" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="studentid" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Ruhithpasha/College_web_dev/punith/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<student xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="student.xsd" studentid="S12345">
  <name>gcu</name>
  <studentInfo>
    <studentName>punith</studentName>
    <studentId>S12345</studentId>
    <studentAge>20</studentAge>
    <studentGender>Male</studentGender>
    <course>Computer Science</course>
  </studentInfo>
  <studentInfo>
    <studentName>ruhith</studentName>
    <studentId>S12346</studentId>
    <studentAge>22</studentAge>
    <studentGender>male</studentGender>
    <course>Mathematics</course>
  </studentInfo>
  <studentsubjects>
    <firstsubject>Mathematics</firstsubject>
    <secondsubject>Physics</secondsubject>
    <thirdsubject>Chemistry</thirdsubject>
    <fourthsubject>Biology</fourthsubject>
  </studentsubjects>
  <activities>
    <curicularactivities>badminton</curicularactivities>
    <sportsactivities>cricket</sportsactivities>
  </activities>
</student>
